name: mdwriter
description: A markdown editor with AI assistance.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  provider: ^6.1.1
  file_picker: ^6.1.1
  path_provider: ^2.1.2
  flutter_markdown: ^0.6.18
  shared_preferences: ^2.2.0
  http: ^1.2.0
  flutter_math_fork: ^0.7.3
  markdown: ^7.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true
